/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {
        Ponto a = new Ponto(10,7);
        Ponto b = new Ponto(10, 5);

        System.out.println(a.calcularDistancia(b));

        System.out.println(a);
    }
}
