/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {
        Navio n1 = new Navio(3,3,true,'C');

        System.out.println(n1.isAtingido(3,4));
    }
}
