/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner leitor = new Scanner(System.in);
        String[] texto = {"1   - ", "5   - ", "10  - ", "25  - ", "50  - ", "100 - "};
        int[] moedas = new int[6];
        double soma = 0;
        int moeda = -1;

        while(moeda != 0){
            System.out.print("Digite sua moeda: ");
            moeda = leitor.nextInt();
            switch(moeda) {
                case 1:
                    moedas[0]++;
                    soma += moeda;
                    break;
                case 5:
                    moedas[1]++;
                    soma += moeda;
                    break;
                case 10:
                    moedas[2]++;
                    soma += moeda;
                    break;
                case 25:
                    moedas[3]++;
                    soma += moeda;
                    break;
                case 50:
                    moedas[4]++;
                    soma += moeda;
                    break;
                case 100:
                    moedas[5]++;
                    soma += moeda;
                    break;
            }
        }

        for (int i = 0; i < moedas.length; i++) {
            System.out.println(texto[i] + moedas[i]);
        }

        System.out.println("R$" + String.format("%.2f",(soma / 100)));

        leitor.close();
    }
}
