/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import org.checkerframework.checker.units.qual.C;

public class App {
    public static void main(String[] args) {


        Estudante e = new Estudante("Kauan Oliveira Freitas", "ADS", 12345);

        System.out.println(e.getTotal());

        Estudante f = new Estudante("Kauan Oliveira Freitas", "ADS", 12345);

        System.out.println(e.getTotal());

        Estudante g = new Estudante("Kauan Oliveira Freitas", "ADS", 12345);

        System.out.println(e.getTotal());
    }
}
