/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import org.checkerframework.checker.units.qual.C;

public class App {
    public static void main(String[] args) {
        Pessoa p1 = new Pessoa("Kauan Oliveira Freitas", "082.622.422-95");
        Pessoa p2 = new Pessoa("Lívia Maria Ferreira da Silva", "123.456.789.10");

        Pessoa p3 = new Pessoa();
        
        System.out.println("Nome: " + p1.getNome());
        System.out.println("CPF: " + p1.getCpf());

        System.out.println("------------------------------------------------------");

        System.out.println("Nome: " + p2.getNome());
        System.out.println("CPF: " + p2.getCpf());
    }
}
