/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import ads.poo.produtos.Dimensao;
import ads.poo.produtos.SemFio;
import ads.poo.produtos.Telefone;

public class App {

    public static void main(String[] args) {
        Telefone telefone = new Telefone(1234,"1234-12","ABC",12,new Dimensao(10,10,10));

        SemFio semFio = new SemFio(12345678,"1234-1234","ABCabc",15,new Dimensao(2,10,15),12,10,10);


    }
}
