/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import edu.princeton.cs.algs4.Draw;
import edu.princeton.cs.algs4.DrawListener;

import java.awt.*;
import java.util.Random;

public class App implements DrawListener {

    private Draw draw;
    private Random r;
    private double tamanhoPincel;

    public App() {
        this.draw = new Draw();
        this.draw.addListener(this);
        this.r = new Random();
        tamanhoPincel = 0.05;
    }

    public static void main(String[] args) {
        App app = new App();
    }

    @Override
    public void mousePressed(double x, double y) {
        this.draw.setPenColor(r.nextInt(256), r.nextInt(256), r.nextInt(256));
        this.draw.filledCircle(x,y,tamanhoPincel);
    }

    @Override
    public void mouseDragged(double x, double y) {
        this.draw.setPenColor(r.nextInt(256), r.nextInt(256), r.nextInt(256));
        this.draw.filledCircle(x,y,tamanhoPincel);
    }

    @Override
    public void keyTyped(char c) {
        if (c == 'c') {
            draw.clear(Color.white);
        }
        if (c == '+') {
            tamanhoPincel += 0.05;
        }
        if (c == '-') {
            tamanhoPincel -= 0.05;
        }
    }


}


// A cada click fazer um circulo de cor aleatorio RGB
// Quando apertar a tecla C limpar a tela inteira