/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import ads.poo.veiculos.Ferrari;
import ads.poo.veiculos.Veiculo;

public class App {

    public static void main(String[] args) {
        Veiculo f = new Ferrari(0,0);


    }
}
