/*
 * This source file was generated by the Gradle 'init' task
 */
package poo.ads;

public class App {

    public static void main(String[] args) {

        // Enumerações
        DiaDaSemana[] aulas = {DiaDaSemana.TER, DiaDaSemana.QUI};

        int disco = aulas[0].getDiaNum();

        DiaDaSemana relatorio = DiaDaSemana.getByDiaNum(disco);

        if (relatorio != null) {
            System.out.println(relatorio);
        }

        switch (relatorio) {
            case DOM -> System.out.printf("não tem aula");
            case SAB -> System.out.println("alguns tem aula");
            default -> System.out.println("pode ter aula");
        }
    }
}
