/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {
        Conta conta = new Conta(12);

        try {
            conta.saque(-1);
        } catch (SaldoInsuficienteException | ValorNegativoException e) {
            System.err.println(e.getMessage());
        }
    }
}