/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import edu.princeton.cs.algs4.Draw;

public class App {

    private Draw draw;
    public App() {
        this.draw = new Draw();
        draw.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        this.draw.setCanvasSize(1000, 600);
        this.draw.setXscale(0, 1000);
        this.draw.setYscale(0, 600);
    }

    public static void main(String[] args) {

        App app = new App();

        Grade g1 = new Grade(100,100);
        Grade g2 = new Grade(540,100);

        g1.desenhar(app.draw);
        g2.desenhar(app.draw);

        Navio n1 = new Navio(3,'D','P',true, g1);

        n1.desenhar(app.draw);

    }
}
