/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {
        Buzz buzz1 = new Buzz();

        System.out.println(buzz1.asas());
        System.out.println(buzz1.asas());

        System.out.println(buzz1.capacete());
        System.out.println(buzz1.capacete());

        System.out.println(buzz1.laser());

        System.out.println(buzz1.golpe());

        System.out.println(buzz1.falar());
    }
}
