/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {
        Horario h = new Horario(23,59,59);
        Horario h2 = new Horario(20,59,59);

        System.out.println(h.extenso());

        System.out.println(h.converterSegundos());

        System.out.println(h.compararHorarios(h2));
    }
}
