/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    public static void main(String[] args) {
        Carro fuscaAzul = new Carro();
        Carro golVerde = new Carro();

        fuscaAzul.setModelo("Fusca");
        fuscaAzul.setCor("azul");
        fuscaAzul.setVelocidadeAtual(10);

        golVerde.setModelo("Gol");
        golVerde.setCor("verde");
        golVerde.setVelocidadeAtual(30);

        System.out.println(fuscaAzul.escreverMensagem());

        System.out.println(golVerde.escreverMensagem());
    }
}
