/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    public static void main(String[] args) {
        Carro carroA = new Carro();
        Carro carroB = new Carro();

        carroA.setModelo("Fusca");
        carroA.setCor("azul");
        carroA.setVelocidadeAtual(10);

        carroB.setModelo("Gol");
        carroB.setCor("verde");
        carroB.setVelocidadeAtual(30);

        System.out.println(carroA.escreverMensagem());

        System.out.println(carroB.escreverMensagem());
    }
}
